# Generated by Django 5.2.7 on 2026-06-17 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان کمپین')),
                ('apply_to', models.CharField(choices=[('all', 'همه مجصولات'), ('product', 'یک محصول'), ('category', 'یک دسته')], default='all', max_length=20, verbose_name='اعمال روی')),
                ('discount_type', models.CharField(choices=[('percent', 'درصدی'), ('amount', 'تومانی')], max_length=10, verbose_name='نوع تخفثف')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='مقدار تخفیف')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='دسته بندی')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=100, verbose_name='کوپن')),
                ('apply_to', models.CharField(choices=[('cart', 'سبد خرید'), ('product', 'یک محصول')], default='cart', max_length=20, verbose_name='اعمال روی')),
                ('discount_type', models.CharField(choices=[('percent', 'درصدی'), ('amount', 'تومانی')], max_length=10, verbose_name='نوع تخفثف')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='مقدار تخفیف')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='محصول')),
            ],
        ),
    ]
