# Generated by Django 5.2.7 on 2026-08-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('pending', 'pending'), ('unsuccessful', 'unsuccessful')], default='pending', verbose_name='وضعیت تراکنش'),
        ),
    ]
