# Generated by Django 5.2.7 on 2026-08-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'موفق'), ('pending', 'در انتظار'), ('unsuccessful', 'ناموفق')], default='pending', verbose_name='وضعیت تراکنش'),
        ),
    ]
