# Generated by Django 5.2.7 on 2026-06-30 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_user_email'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت کل')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='بعد تخفیف')),
                ('final_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت نهای')),
                ('transaction_id', models.UUIDField(blank=True, null=True, verbose_name='کد پیگیری')),
                ('payment', models.BooleanField(default=False, verbose_name='پرداخت')),
                ('status', models.CharField(choices=[('در حال پردازش', 'در حال پردازش'), ('آماده برای ارسال', 'آماده برای ارسال'), ('محصول ارسال شد', 'محصول ارسال شد'), ('تحویل پست داده شد', 'تحویل پست داده شد'), ('محصول به مشتری تحویل داده شد', 'محصول به مشتری تحویل داده شد'), ('لغو توسط مشتری', 'لغو توسط مشتری'), ('لغو توسط فروشنده', 'لغو توسط فروشنده'), ('مرحوع شد', 'مرحوع شد')], default='در حال پردازش', verbose_name='وضعیت محصول')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('address_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_user', to='account.addressuser', verbose_name='آدرس')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name_plural': 'سفارش ها',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='مقدار محصول')),
                ('price_at_purchase', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت زمان خرید')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='مخصولات')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created'], name='order_order_created_708daa_idx'),
        ),
    ]
