# Generated by Django 5.2.7 on 2026-07-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'آیتم سفارش ها'},
        ),
        migrations.AddField(
            model_name='order',
            name='post_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='هزینه پستی'),
        ),
    ]
