# Generated by Django 5.2.7 on 2026-08-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_options_order_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('در حال پردازش', 'در حال پردازش'), ('آماده برای ارسال', 'آماده برای ارسال'), ('محصول ارسال شد', 'محصول ارسال شد'), ('تحویل پست داده شد', 'تحویل پست داده شد'), ('محصول به مشتری تحویل داده شد', 'محصول به مشتری تحویل داده شد'), ('لغو توسط مشتری', 'لغو توسط مشتری'), ('لغو توسط فروشنده', 'لغو توسط فروشنده'), ('مرحوع شد', 'مرحوع شد')], default='در حال پردازش', verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد پیگیری'),
        ),
    ]
